### PR TITLE
Scala 2.13

### PR DESCRIPTION
**Pull request by Clever-Cavy**
Key notes:
- update akka to 2.6
- cross-compile to Scala 2.12 and 2.13; end of support Scala 2.11
- set version to 0.3.0

### CODE REVIEW

**Comment by Clever-Cavy** [comment]
Hey, @maciej, I really like your library! Could you consider to compile it to Scala 2.13?

**Comment by maciej** [comment]
Thanks @Clever-Cavy. I've released your changes.

**Comment by maciej** [comment]
I'm no longer working with Scala day-to-day. @Clever-Cavy would you mind checking for me if the release went well?

**Comment by Clever-Cavy** [comment]
Yes, sure. I will keep on eye.

**Pull request merged**
